version: '3.3'

services:
  rabbit:
    image: rabbitmq:3.8.16-management
    ports:
        - "5672:5672"
        - "15672:15672"
    networks: 
        - backend

networks:
  backend:
    name: ms_publisher_subscriber
    driver: bridge